w = window.innerWidth;
h = window.innerHeight;

colorA = '#051205';
colorB = '#8476F5';
colorC = '#6BF55D';
colorD = '#F58B45';
colorE = '#FFF0E6';

/*
colorA = '#121212';
colorB = '#6EB9F5';
colorC = '#F1F555';
colorD = '#F5433D';
colorE = '#E0E0E0';
  */
console.log('W=', w, " H=", h);
if (h < w) {
    w = (h / 3) * 0.75;// * ( h / w );
    h = w * 3;
}
else {
    w = (w / 3) * 0.75;// * ( w / h );
    h = w * 3;
}
var gauge_0 = new LinearGauge({
    renderTo: 'linear-gauge-0',
    width: w,
    height: h,
    minValue: -50,
    maxValue: 50,
    title: "Температура",
    value: 0,
    units: '°C',

    majorTicks: [
        -50,
        -40,
        -30,
        -20,
        -10,
        0,
        10,
        20,
        30,
        40,
        50
    ],
    minorTicks: 0,
    strokeTicks: true,
    animatedValue: true,//false, //true,
    animateOnInit: true,//false, //true,
   
    border: true,
    numbersMargin: 1,
    numberSide: "both",
    //разрядность 
    valueInt: 3,
    //знаки после запятой
    valueDec: 2,
    majorTicksInt: 1,
    majorTicksDec: 0,
    animation: true,
    animationDuration: 500,
    animationRule: "linear", //cycle
    colorPlate: colorA,
    colorPlateEnd: "",
    colorMajorTicks: "#444",
    colorMinorTicks: "#666",
    colorTitle: colorE,
    colorUnits: colorE,
    colorNumbers: colorE,
    colorNeedle: colorB,
    colorNeedleEnd: colorB,
    colorValueText: "#444",
    colorValueTextShadow: "rgba(0,0,0,0.3)",
    colorBorderShadow: "rgba(0,0,0,0.5)",
    colorBorderOuter: "#ddd",
    colorBorderOuterEnd: "#aaa",
    colorBorderMiddle: "#eee",
    colorBorderMiddleEnd: "#f0f0f0",
    colorBorderInner: "#fafafa",
    colorBorderInnerEnd: "#ccc",
    colorValueBoxRect: "#888",
    colorValueBoxRectEnd: "#666",
    colorValueBoxBackground: "#babab2",
    colorValueBoxShadow: "rgba(0,0,0,1)",
    colorNeedleShadowUp: colorA,
    colorNeedleShadowDown: colorA,
    colorBarStroke: "#222",
    colorBar: colorE,
    colorBarProgress: colorD,
    colorBarShadow: colorA,
    //colorBarEnd : "rgba(255,255,255,0.99)",
    //colorBarProgressEnd : "rgba(0,255,0,0.99)",
    fontNumbers: "Arial",
    fontTitle: "Arial",
    fontUnits: "Arial",
    fontValue: "Arial",
    fontNumbersSize: 28,
    fontTitleSize: 22,
    fontUnitsSize: 30,
    fontValueSize: 24,
    fontNumbersStyle: "normal",
    fontTitleStyle: "normal",
    fontUnitsStyle: "normal",
    fontValueStyle: "normal",
    fontNumbersWeight: "normal",
    fontTitleWeight: "normal",
    fontUnitsWeight: "normal",
    fontValueWeight: "normal",
    needle: true,
    needleShadow: true,
    needleType: "arrow",
    needleSide: "both",
    needleStart: 5,
    needleEnd: 85,
    needleWidth: 10,
    borderOuterWidth: 1,
    borderMiddleWidth: 0,
    borderInnerWidth: 0,
    borderShadowWidth: 0,
    valueBox: true,
    valueBoxStroke: 5,
    valueBoxWidth: 0,
    valueText: "",
    valueTextShadow: true,
    valueBoxBorderRadius: 2.5,
    highlights: [
        {
            "from": -50,
            "to": 50,
            "color": colorC
        },
       

    ],
    highlightsWidth: 15,
    barWidth: 10,
    barBeginCircle: 0,
    barStrokeWidth: 0,
    barProgress: true,
    barShadow: 0,
    ticksAngle: 270,
    tickSide: "both",
    startAngle: 45,
    colorNeedleCircleOuter: "#f0f0f0",
    //colorNeedleCircleOuter : "#000000",
    colorNeedleCircleOuterEnd: "#ccc",
    colorNeedleCircleInner: "#e8e8e8",
    colorNeedleCircleInnerEnd: "#f5f5f5",
    needleCircleSize: 10,
    needleCircleInner: true,
    needleCircleOuter: true,
    animationTarget: "needle",
    animatedValue: true,
    useMinPath: false,
}).draw();

var gauge_1 = new LinearGauge({
    renderTo: 'linear-gauge-1',
    width: w,
    height: h,
    minValue: 0,
    maxValue: 100,
    title: "Влажность",
    value: 0,
    units: '%',
    majorTicks: [
        0,
        10,
        20,
        30,
        40,
        50,
        60,
        70,
        80,
        90,
        100
    ],
    minorTicks: 0,
    strokeTicks: true,
    animatedValue: true,//false, //true,
    animateOnInit: true,//false, //true,
   
    border: true,
    numbersMargin: 1,
    numberSide: "both",
    //разрядность 
    valueInt: 3,
    //знаки после запятой
    valueDec: 2,
    majorTicksInt: 1,
    majorTicksDec: 0,
    animation: true,
    animationDuration: 500,
    animationRule: "linear", //cycle
    colorPlate: colorA,
    colorPlateEnd: "",
    colorMajorTicks: "#444",
    colorMinorTicks: "#666",
    colorTitle: colorE,
    colorUnits: colorE,
    colorNumbers: colorE,
    colorNeedle: colorB,
    colorNeedleEnd: colorB,
    colorValueText: "#444",
    colorValueTextShadow: "rgba(0,0,0,0.3)",
    colorBorderShadow: "rgba(0,0,0,0.5)",
    colorBorderOuter: "#ddd",
    colorBorderOuterEnd: "#aaa",
    colorBorderMiddle: "#eee",
    colorBorderMiddleEnd: "#f0f0f0",
    colorBorderInner: "#fafafa",
    colorBorderInnerEnd: "#ccc",
    colorValueBoxRect: "#888",
    colorValueBoxRectEnd: "#666",
    colorValueBoxBackground: "#babab2",
    colorValueBoxShadow: "rgba(0,0,0,1)",
    colorNeedleShadowUp: colorA,
    colorNeedleShadowDown: colorA,
    colorBarStroke: "#222",
    colorBar: colorE,
    colorBarProgress: colorD,
    colorBarShadow: colorA,
    //colorBarEnd : "rgba(255,255,255,0.99)",
    //colorBarProgressEnd : "rgba(0,255,0,0.99)",
    fontNumbers: "Arial",
    fontTitle: "Arial",
    fontUnits: "Arial",
    fontValue: "Arial",
    fontNumbersSize: 28,
    fontTitleSize: 22,
    fontUnitsSize: 30,
    fontValueSize: 24,
    fontNumbersStyle: "normal",
    fontTitleStyle: "normal",
    fontUnitsStyle: "normal",
    fontValueStyle: "normal",
    fontNumbersWeight: "normal",
    fontTitleWeight: "normal",
    fontUnitsWeight: "normal",
    fontValueWeight: "normal",
    needle: true,
    needleShadow: true,
    needleType: "arrow",
    needleSide: "both",
    needleStart: 5,
    needleEnd: 85,
    needleWidth: 10,
    borderOuterWidth: 1,
    borderMiddleWidth: 0,
    borderInnerWidth: 0,
    borderShadowWidth: 0,
    valueBox: true,
    valueBoxStroke: 5,
    valueBoxWidth: 0,
    valueText: "",
    valueTextShadow: true,
    valueBoxBorderRadius: 2.5,
    highlights: [
        {
            "from": 0,
            "to": 100,
            "color": colorC
        }

    ],
    highlightsWidth: 15,
    barWidth: 10,
    barBeginCircle: 0,
    barStrokeWidth: 0,
    barProgress: true,
    barShadow: 0,
    ticksAngle: 270,
    tickSide: "both",
    startAngle: 45,
    //colorNeedleCircleOuter : "#f0f0f0",
    //colorNeedleCircleOuter : "#000000",
    colorNeedleCircleOuterEnd: "#ccc",
    colorNeedleCircleInner: "#e8e8e8",
    colorNeedleCircleInnerEnd: "#f5f5f5",
    needleCircleSize: 10,
    needleCircleInner: true,
    needleCircleOuter: true,
    animationTarget: "needle",
    animatedValue: true,
    useMinPath: false,
}).draw();


var gauge_2 = new LinearGauge({
    renderTo: 'linear-gauge-2',
    width: w,
    height: h,
    minValue: -120,
    maxValue: 0,
    title: "WiFi",
    value: 0,
    units: 'dBm',

    majorTicks: [
        -120,
        -110,
        -100,
        -90,
        -80,
        -70,
        -60,
        -50,
        -40,
        -30,
        -20,
        -10,
        0
    ],
    minorTicks: 0,
    strokeTicks: true,
    animatedValue: true,//false, //true,
    animateOnInit: true,//false, //true,

    border: true,
    numbersMargin: 1,
    numberSide: "both",
    //разрядность 
    valueInt: 3,
    //знаки после запятой
    valueDec: 2,
    majorTicksInt: 1,
    majorTicksDec: 0,
    animation: true,
    animationDuration: 500,
    animationRule: "linear", //cycle
    colorPlate: colorA,
    colorPlateEnd: "",
    colorMajorTicks: "#444",
    colorMinorTicks: "#666",
    colorTitle: colorE,
    colorUnits: colorE,
    colorNumbers: colorE,
    colorNeedle: colorB,
    colorNeedleEnd: colorB,
    colorValueText: "#444",
    colorValueTextShadow: "rgba(0,0,0,0.3)",
    colorBorderShadow: "rgba(0,0,0,0.5)",
    colorBorderOuter: "#ddd",
    colorBorderOuterEnd: "#aaa",
    colorBorderMiddle: "#eee",
    colorBorderMiddleEnd: "#f0f0f0",
    colorBorderInner: "#fafafa",
    colorBorderInnerEnd: "#ccc",
    colorValueBoxRect: "#888",
    colorValueBoxRectEnd: "#666",
    colorValueBoxBackground: "#babab2",
    colorValueBoxShadow: "rgba(0,0,0,1)",
    colorNeedleShadowUp: colorA,
    colorNeedleShadowDown: colorA,
    colorBarStroke: "#222",
    colorBar: colorE,
    colorBarProgress: colorD,
    colorBarShadow: colorA,
    //colorBarEnd : "rgba(255,255,255,0.99)",
    //colorBarProgressEnd : "rgba(0,255,0,0.99)",
    fontNumbers: "Arial",
    fontTitle: "Arial",
    fontUnits: "Arial",
    fontValue: "Arial",
    fontNumbersSize: 28,
    fontTitleSize: 22,
    fontUnitsSize: 30,
    fontValueSize: 24,
    fontNumbersStyle: "normal",
    fontTitleStyle: "normal",
    fontUnitsStyle: "normal",
    fontValueStyle: "normal",
    fontNumbersWeight: "normal",
    fontTitleWeight: "normal",
    fontUnitsWeight: "normal",
    fontValueWeight: "normal",
    needle: true,
    needleShadow: true,
    needleType: "arrow",
    needleSide: "both",
    needleStart: 5,
    needleEnd: 85,
    needleWidth: 10,
    borderOuterWidth: 1,
    borderMiddleWidth: 0,
    borderInnerWidth: 0,
    borderShadowWidth: 0,
    valueBox: true,
    valueBoxStroke: 5,
    valueBoxWidth: 0,
    valueText: "",
    valueTextShadow: true,
    valueBoxBorderRadius: 2.5,
    highlights: [
        {
            "from": -120,
            "to": 0,
            "color": colorC
        },

    ],
    highlightsWidth: 15,
    barWidth: 10,
    barBeginCircle: 0,
    barStrokeWidth: 0,
    barProgress: true,
    barShadow: 0,
    ticksAngle: 270,
    tickSide: "both",
    startAngle: 45,
    //colorNeedleCircleOuter : "#f0f0f0",
    //colorNeedleCircleOuter : "#000000",
    colorNeedleCircleOuterEnd: "#ccc",
    colorNeedleCircleInner: "#e8e8e8",
    colorNeedleCircleInnerEnd: "#f5f5f5",
    needleCircleSize: 10,
    needleCircleInner: true,
    needleCircleOuter: true,
    animationTarget: "needle",
    animatedValue: true,
    useMinPath: false,
}).draw();




